### ISSUE TITLE
EWAHCompressedBitmap.set is slow when more than 1 million elements are inserted

### ISSUE THREAD

**Issue by sxpujs** [lemire/javaewah#56]
Is there a quick method to add a lot of elements to EWAHCompressedBitmap? for example:

    EWAHCompressedBitmap bitmap = new EWAHCompressedBitmap();
    Random ran = new Random();
    for (int index = 0; index < 1_000_000; index++) {
      bitmap.set(ran.nextInt(5_000_000));
    }
    System.out.println("complete!");

**Comment by lemire** [comment]
Here is what the documentation states:

Though you can set the bits in any order (e.g., set(100), set(10), set(1), you will typically get better performance if you set the bits in increasing order (e.g., set(1), set(10), set(100)). Setting a bit that is larger than any of the current set bit is a constant time operation. Setting a bit that is smaller than an already set bit can require time proportional to the compressed size of the bitmap, as the bitmap may need to be rewritten. 

Reference:

http://lemire.me/docs/javaewah/com/googlecode/javaewah/EWAHCompressedBitmap.html#set-int-

Have you tried setting the bits in order, as recommended?

Otherwise, if you must use random order, have you considered competitive alternatives like Roaring?

https://github.com/lemire/RoaringBitmap/

**Comment by sxpujs** [comment]
Lemire, thanks for your reply, RoaringBitmap is a better option in my case.
